const Data = [
  {
    id: 1,
    language: 'JAVASCRIPT',
    title: 'Donnie-Bank Transactions',
    tag: 'BANK TRANSACTIONS',
    highlights: 'JAVASCRIPT',
    image: "../../IMG/Donnie's-Bank.JPG",
    details:
      'Donnie-Bank  is a app that lets customers to login tho thier bank account and see the all the transactions, request a loan or transfer money to frined who uses same bank.',
    link: 'https://donnie-bank-js.netlify.app/',
  },
  {
    id: 2,
    language: 'JAVASCRIPT',
    title: 'Productivity Booster',
    tag: 'MY DAILY PRODUCTIVITY',
    highlights: 'JAVASCRIPT AJAX/API',
    image: '../../IMG/Productivity booster.PNG',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 3,
    language: 'JAVASCRIPT',
    title: 'Random Dice Game',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'JAVASCRIPT',
    image: '../../IMG/Random-Dice-Game.JPG',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 4,
    language: 'JAVASCRIPT',
    title: 'Random Dice Game',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'JAVASCRIPT OOP',
    image: '../../IMG/Forkify-JS.JPG',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 5,
    language: 'JAVASCRIPT',
    title: 'Random Dice Game',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'JavaScript Arrays',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 6,
    language: 'JAVASCRIPT',
    title: 'Random Dice Game',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'JavaScript Arrays',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 7,
    language: 'CSS/SASS',
    title: 'CSS PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'CSS PROJECT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 8,
    language: 'CSS/SASS',
    title: 'CSS PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'CSS PROJECT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 9,
    language: 'CSS/SASS',
    title: 'CSS PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'CSS PROJECT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 10,
    language: 'CSS/SASS',
    title: 'CSS PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'CSS PROJECT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 11,
    language: 'CSS/SASS',
    title: 'CSS PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'CSS PROJECT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 12,
    language: 'CSS/SASS',
    title: 'CSS PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'CSS PROJECT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 13,
    language: 'REACT',
    title: 'REACT APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 14,
    language: 'REACT',
    title: 'REACT APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 15,
    language: 'REACT',
    title: 'REACT APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 16,
    language: 'REACT',
    title: 'REACT APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 17,
    language: 'REACT',
    title: 'REACT APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 18,
    language: 'REACT',
    title: 'REACT APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 19,
    language: 'PYTHON',
    title: 'PYTHON APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 20,
    language: 'PYTHON',
    title: 'PYTHON APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 21,
    language: 'PYTHON',
    title: 'PYTHON APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 22,
    language: 'PYTHON',
    title: 'PYTHON APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 23,
    language: 'PYTHON',
    title: 'PYTHON APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 24,
    language: 'PYTHON',
    title: 'PYTHON APP',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 25,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 26,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 27,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 28,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 29,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 30,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: '../../IMG/',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
];

export default Data;
