const Data = [
  {
    id: 1,
    language: 'JAVASCRIPT',
    title: 'DONNIE-BANK Transactions',
    tag: 'BANK TRANSACTIONS',
    highlights: 'JAVASCRIPT ARRAY',
    image: './IMG/JS-BANK400x300.jpg',
    details:
      'Donnie-Bank  is a app that lets customers to login to thier bank account and see the all the transactions, request a loan or transfer money to frined who uses same bank.',
    link: 'https://donnie-bank-js.netlify.app/',
    img: [
      '../IMG/JS-BANK400x300.jpg',
      '../IMG/ProductivityApp.JPG',
      '../IMG/My-Portfolio-React.JPG',
    ],
  },
  {
    id: 2,
    language: 'JAVASCRIPT',
    title: 'PRODUCTIVITY Booster',
    tag: 'MY DAILY PRODUCTIVITY',
    highlights: 'JAVASCRIPT AJAX/API',
    image: './IMG/ProductivityApp.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 3,
    language: 'JAVASCRIPT',
    title: 'DICE GAME',
    tag: 'DICE GAME FOR TWO PLAYERS',
    highlights: 'JAVASCRIPT DOM MANIPULATION',
    image: './IMG/Random-Dice-Game.JPG',
    details:
      'Random Dice game lets two people to play. Player rolls the dice until gets to 20 points. If player hit number 1 looses all the accumelated points. Player has option of holding current points and pass the turn other player.',
    link: 'https://random-dice-number-js.netlify.app/',
  },
  {
    id: 4,
    language: 'JAVASCRIPT',
    title: 'FIND RECIPE',
    tag: 'OVER 500 COOKING RECIPES',
    highlights: 'JAVASCRIPT API OOP',
    image: './IMG/Forkify-JS.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/Recipe-Finder-JS-OOP',
  },
  {
    id: 5,
    language: 'JAVASCRIPT',
    title: 'GUESS MY NUMBER GAME',
    tag: 'GUESS COMPUTER"S NUMBER',
    highlights: 'JAVASCRIPT DOM MANIPULATION',
    image: './IMG/Guess my number.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://laughing-austin-551ef0.netlify.app/',
  },
  {
    id: 6,
    language: 'JAVASCRIPT',
    title: 'MY TODOS',
    tag: 'JAVASCRIPT TODO APP',
    highlights: 'JAVASCRIPT',
    image: './IMG/Day planner JS.PNG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/Homework-5',
  },
  {
    id: 7,
    language: 'CSS-SASS',
    title: 'DONNIE-BANK Landing Page',
    tag: 'Bank Landing Page',
    highlights: 'CSS FLOAT',
    image: './IMG/Bank-landing page.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://donnie-bank-advanced-dom-js.netlify.app/',
  },
  {
    id: 8,
    language: 'CSS-SASS',
    title: 'UZVOYAGE Travel-Agency',
    tag: 'UZVOYAGE TRAVEL AGENCY',
    highlights: 'CSS-SASS GRID/FLEXBOX',
    image: './IMG/Uz-Voyage main page.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://uz-voyage-travel.netlify.app/',
  },
  {
    id: 9,
    language: 'CSS-SASS',
    title: 'REAL ESTATE Website',
    tag: "Real Estate Agency's landing page",
    highlights: 'CSS-SASS GRID',
    image: './IMG/CSS-GRID Real-Estate.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://css-grid-real-estate-page.netlify.app/',
  },
  {
    id: 10,
    language: 'CSS-SASS',
    title: 'TRILLO Booking-Agency',
    tag: 'Booking Hotel Car rental and flight',
    highlights: 'CSS-SASS Flexbox',
    image: './IMG/Flexbox-Travel-agency.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://flexbox-travel-agency-page.netlify.app/',
  },
  {
    id: 11,
    language: 'CSS-SASS',
    title: 'TOUR AGENCY Info Page',
    tag: 'Tour agency Blog Page',
    highlights: 'CSS-SASS FLOAT',
    image: './IMG/CSS Float TourAgency.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://float-advanced-css-sass-website-uz-voyage.netlify.app/',
  },
  {
    id: 12,
    language: 'CSS-SASS',
    title: 'FIND RECIPE Page',
    tag: 'Recipe Finder Page',
    highlights: 'CSS-SASS',
    image: './IMG/Forkify-JS.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/Recipe-Finder-JS-OOP',
  },
  {
    id: 13,
    language: 'REACT',
    title: 'Portfolio Repos Component',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT Props',
    image: './IMG/Repos React Component.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://mralimov.github.io/My-Portfolio/',
  },
  {
    id: 14,
    language: 'REACT',
    title: 'REACT PORTFOLIO',
    tag: 'My React Portfolio',
    highlights: 'REACT',
    image: './IMG/My-react-expenses.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/My-React-Expenses',
  },
  {
    id: 15,
    language: 'REACT',
    title: 'ORDER FOOD React/Hooks',
    tag: 'Searching books in Google',
    highlights: 'REACT',
    image: './IMG/Order Food React-hooks.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://order-food-app-react.netlify.app/',
  },
  {
    id: 16,
    language: 'REACT',
    title: 'DIRECTORY SEARCH',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: './IMG/Employee-Directory-React.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/React-Employee-Directory',
  },
  {
    id: 17,
    language: 'REACT',
    title: 'REACT PORTFOLIO',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'REACT',
    image: './IMG/My-Portfolio-React.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/My-React-Portfolio',
  },
  {
    id: 18,
    language: 'REACT',
    title: 'Redux Add to Cart',
    tag: 'Redux managing cart items state ',
    highlights: 'REACT',
    image: './IMG/Redux-add-to-cart.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://redux-add-to-cart.netlify.app/',
  },
  {
    id: 19,
    language: 'PYTHON',
    title: 'HANGMAN GAME',
    tag: 'Hangman game Python',
    highlights: 'PYTHON',
    image: './IMG/Hangman Game.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/HANGMAN-game-Python',
  },
  {
    id: 20,
    language: 'PYTHON',
    title: 'US .STATES GAME',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: './IMG/US.State Game Python.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/',
  },
  {
    id: 21,
    language: 'PYTHON',
    title: 'TURTLE RACE GAME',
    tag: 'Quiz questions built OOP',
    highlights: 'PYTHON OOP',
    image: './IMG/Turtle game python.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/W',
  },
  {
    id: 22,
    language: 'PYTHON',
    title: 'QUIZ QUESTIONS',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: './IMG/Quiz questions python.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/Quiz-Questions-OOP-Python',
  },
  {
    id: 23,
    language: 'PYTHON',
    title: 'PING-PONG GAME',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: './IMG/PingPong Game Python.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/PONG-GAME-PYTHON',
  },
  {
    id: 24,
    language: 'PYTHON',
    title: 'SNAKE GAME',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'PYTHON',
    image: './IMG/Snake-Game Python.JPG',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov/Snake-Game-Python',
  },
  {
    id: 25,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: './IMG/',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov',
  },
  {
    id: 26,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: './IMG/',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov',
  },
  {
    id: 27,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: './IMG/',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov',
  },
  {
    id: 28,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: './IMG/',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov',
  },
  {
    id: 29,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: './IMG/',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov',
  },
  {
    id: 30,
    language: 'MERN',
    title: 'MERN PROJECT',
    tag: 'DICE GAME FOR TWO PEOPLE',
    highlights: 'MERN',
    image: './IMG/',
    details:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!',
    link: 'https://github.com/mralimov',
  },
];

export default Data;
